### ISSUE TITLE
composer update执行不成功

### ISSUE THREAD

**Issue by wuyongguoke** [fecshop/yii2_fecshop_app_advanced#2]
Problem 1
    - yiisoft/yii2-mongodb 2.1.2 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - yiisoft/yii2-mongodb 2.1.1 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - yiisoft/yii2-mongodb 2.1.0 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - fancyecommerce/fecshop 1.0.0.9 requires yiisoft/yii2-mongodb ~2.1.0 -> satisfiable by yiisoft/yii2-mongodb[2.1.0, 2.1.1, 2.1.2].
    - Installation request for fancyecommerce/fecshop 1.0.0.9 -> satisfiable by fancyecommerce/fecshop[1.0.0.9].

  To enable extensions, verify that they are enabled in those .ini files:
    - D:\wamp64\bin\php\php5.6.25\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by wuyongguoke** [comment]
修改php\php5.6.25\php.ini文件 加载扩展就ok了

**Comment by fancyecommerce** [comment]
恩，需要安装php mongodb的扩展，详细参看：http://www.fancyecommerce.com/2016/05/03/yii2-mongodb%E7%9A%84%E5%AE%89%E8%A3%85%E5%92%8C%E9%85%8D%E7%BD%AE-mongo/

**Comment by wuyongguoke** [comment]
收到，谢谢！已安装php mongodb的扩展，并对应修改了php\php5.6.25\php.ini文件，正在执行安装。




------------------ 原始邮件 ------------------
发件人: "Terry";<notifications@github.com>;
发送时间: 2017年1月5日(星期四) 下午2:55
收件人: "fancyecommerce/yii2_fecshop_app_advanced"<yii2_fecshop_app_advanced@noreply.github.com>; 
抄送: "无为"<514218119@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [fancyecommerce/yii2_fecshop_app_advanced] composer update执行不成功 (#2)




恩，需要安装php mongodb的扩展，详细参看：http://www.fancyecommerce.com/2016/05/03/yii2-mongodb%E7%9A%84%E5%AE%89%E8%A3%85%E5%92%8C%E9%85%8D%E7%BD%AE-mongo/
