### ISSUE TITLE
访问appfront/web(PC端)  报错 PHP Notice – yii\base\ErrorException Undefined index: helper，求教

### ISSUE THREAD

**Issue by wuyongguoke** [fecshop/yii2_fecshop_app_advanced#3]
PHP Notice – yii\base\ErrorException
Undefined index: helper

    1. in E:\data\vhosts\fecshop\vendor\fancyecommerce\fecshop\services\Application.php at line 32
    23242526272829303132333435363738394041

        public function __construct($config = [])
        {
            Yii::$service 		= $this;
            $this->childService = $config;
        }
        /**
         */
        public function getChildService($childServiceName){
            if(!$this->_childService[$childServiceName]){
                $childService = $this->childService;
                if(isset($childService[$childServiceName])){
                    $service = $childService[$childServiceName];
                    $this->_childService[$childServiceName] = Yii::createObject($service);
                }else{
                    throw new InvalidConfigException('Child Service ['.$childServiceName.'] is not find in '.get_called_class().', you must config it! ');
                }
            }
            return $this->_childService[$childServiceName];

2. in E:\data\vhosts\fecshop\vendor\fancyecommerce\fecshop\services\Service.php at line 78 – fecshop\services\Application::__get()
72737475767778798081828384

    } 
 
    /**
     * 如果开启service log，则记录开始的时间。
     */
    protected function beginCall($originMethod,$arguments) {
        if(Yii::$service->helper->log->isServiceLogEnable()){
            $this->_beginCallTime = microtime(true);
        }
    }
 
    /**
     * @param $originMethod and $arguments,魔术方法传递的参数

**Comment by fancyecommerce** [comment]
加QQ：2358269014，详细说明问题
